from typing import Protocol, runtime_checkable


@runtime_checkable
class TCPConnectionProtocol(Protocol):
    """Interface every TCPConnection must implement for the harness."""

    def recv_from_app(self, payload: bytes) -> None: ...
    def recv_from_network(self, packet: bytes) -> None: ...
    def on_timer_expire(self) -> None: ...
    def close(self) -> None: ...

    @property
    def window_base(self) -> int: ...
    @property
    def next_seq(self) -> int: ...
    @property
    def bytes_acked(self) -> int: ...
    @property
    def bytes_delivered(self) -> int: ...
    @property
    def sack_blocks(self) -> list[tuple[int, int]]: ...
    @property
    def state(self) -> str: ...
    @property
    def retransmit_count(self) -> dict[int, int]: ...
    @property
    def app_recv_buffer(self) -> list[bytes]: ...
